[config]
reload_apps = true
set_wallpaper = false  # We'll handle this with hyprpaper directly
mode = "dark"

[config.reload_apps_list]
hyprland = true
kitty = true
rofi = true
mako = true

[[config.custom_keywords]]
name = "colors"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/appearance/colors.conf"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar-colors.css"
output_path = "~/.config/waybar/colors.css"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/colors.conf"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.mako]
input_path = "~/.config/matugen/templates/mako-colors"
output_path = "~/.config/mako/colors"

[templates.vesktop]
input_path = "~/.config/matugen/templates/vesktop-colors.css"
output_path = "~/.config/vesktop/themes/matugen.css"

[templates.qutebrowser]
input_path = "~/.config/matugen/templates/qute-colors.py"
output_path = "~/.config/qutebrowser/colors.py"
