# Matugen generated colors
$background = rgb(12140e)
$foreground = rgb(e2e3d8)
$surface = rgb(12140e)
$surface_bright = rgb(383a32)
$surface_container = rgb(1e201a)
$on_surface = rgb(e2e3d8)

$primary = rgb(b1d18a)
$on_primary = rgb(1f3701)
$primary_container = rgb(344e16)

$secondary = rgb(bfcbad)
$tertiary = rgb(a0d0cc)
$error = rgb(ffb4ab)

# Use these in hyprland config
$active_border = $primary
$inactive_border = $surface_container
