general {
    gaps_in = 2
    gaps_out = 4 
    border_size = 2

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false

    col.active_border = $primary
    col.inactive_border = $on_primary

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}

