# ================================
# ========== Applications ========
# ================================
bind = $mainMod, Q, killactive
bind = $mainMod, T, exec, $terminal
bind = $mainMod, B, exec, $browser
bind = $mainMod, O, exec, $email
bind = $mainMod, M, exec, $music
bind = $mainMod, D, exec, $chat
bind = $mainMod, W, exec, $wallpaper
bind = $mainMod, Y, exec, $files
bind = $mainMod, E, exec, $filegui
bind = $mainMod, A, exec, rofi -show drun
bind = $mainMod, V, exec, cliphist list | rofi -dmenu -p "Clipboard" | cliphist decode | wl-copy
bind = $mainMod, R, exec, ~/.config/waybar/scripts/launch.sh
bind = $mainMod, N, exec, pavucontrol
bind = $mainMod, escape, exec, ~/.config/rofi/scripts/powermenu.sh

# ================================
# ========== Scratchpads =========
# ================================
bind = $mainMod SHIFT, M, togglespecialworkspace, spotify
bind = $mainMod SHIFT, M, exec, pgrep -x spotify || spotify
bind = $mainMod SHIFT, D, togglespecialworkspace, vesktop
bind = $mainMod SHIFT, D, exec, pgrep -x vesktop || vesktop
bind = $mainMod SHIFT, T, exec, ~/.config/hypr/scripts/toggle-scratch-term.sh
bind = $mainMod SHIFT, R, exec, ~/.config/hypr/scripts/toggle-scratch-btop.sh
bind = $mainMod SHIFT, Z, exec, ~/.config/hypr/scripts/toggle-scratch-zeal.sh
