# ================================
# ========== General =============
# ================================

# Starts window indexing at 1
set -g base-index 1     
setw -g pane-base-index 1

# Fills gaps automatically
set -g renumber-windows on

# Faster escape in Neovim
set -sg escape-time 0

# Activate mouse (mostly for terminal copying)
set -g mouse on

set -g history-limit 50000
set -g default-terminal "tmux-256color"

setw -g mode-keys vi
set -g status-keys vi

# ================================
# ========== Keybind =============
# ================================

# "Leader" Key
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Use TMUX Sessionizer script inside of tmux
unbind f
bind-key f display-popup -E -w 80% -h 60% "/home/solyshi/scripts/tmux-sessionizer"

# New window in current path
bind c new-window -c "#{pane_current_path}"

# Reload tmux config
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# Pane splitting more intuitive
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Nvim
bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-h) || tmux select-pane -L"
bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-j) || tmux select-pane -D"
bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-k) || tmux select-pane -U"
bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-l) || tmux select-pane -R"

# ================================
# ========== Plugins =============
# ================================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Continuum Settings
set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

# Initialize TPM (has to be the last line)
run '~/.config/tmux/plugins/tpm/tpm'
