# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# Daemons
exec-once = hyprpaper
exec-once = waybar
exec-once = mako

# Clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Set WP
exec-once = ~/.config/theme/apply.sh

# Apps
exec-once = [workspace 1 silent] kitty
exec-once = [workspace 2 silent] qutebrowser
exec-once = [workspace 9 silent] thunderbird
exec-once = [workspace 0 silent] tradingview
