wallpaper {
    monitor = DP-3
    path = ~/wallpapers/.local/share/wallpapers/wallpaper_forest.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DVI-D-1
    path = ~/wallpapers/.local/share/wallpapers/wallpaper_forest.jpg
    fit_mode = cover
}
