source = ~/.config/hypr/functionality/programs.conf
source = ~/.config/hypr/functionality/autostart.conf
source = ~/.config/hypr/functionality/input.conf

source = ~/.config/hypr/appearance/colors.conf
source = ~/.config/hypr/appearance/general.conf
source = ~/.config/hypr/appearance/layouts.conf
source = ~/.config/hypr/appearance/theme.conf
source = ~/.config/hypr/appearance/monitors.conf

source = ~/.config/hypr/keybinds/main.conf

source = ~/.config/hypr/rules/windowrules.conf
source = ~/.config/hypr/rules/layerrules.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
