# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#     name = no-gaps-wtv1
#     match:float = false
#     match:workspace = w[tv1]
#
#     border_size = 0
#     rounding = 0
# }
#
# windowrule {
#     name = no-gaps-f1
#     match:float = false
#     match:workspace = f[1]
#
#     border_size = 0
#     rounding = 0
# }

# ================================
# ======= Workspace Rules ========
# ================================
windowrule {
    name = ws-browser
    match:class = org.qutebrowser.qutebrowser
    workspace = 2
}
windowrule {
    name = ws-files
    match:class = org.kde.dolphin
    workspace = 3
}
windowrule {
    name = ws-mail
    match:class = org.mozilla.Thunderbird
    workspace = 9
}

windowrule {
    name = ws-trading
    match:class = TradingView
    workspace = 10
}

# ================================
# ======= Scratchpads ============
# ================================
windowrule {
    name = scratchpad-spotify
    match:class = spotify
    workspace = special:spotify
    float = yes
    size = 1200 750
    center = yes
}
windowrule {
    name = scratchpad-vesktop
    match:class = vesktop
    workspace = special:vesktop
    float = yes
    size = 1200 800
    center = yes
}
windowrule {
    name = scratchpad-terminal
    match:class = kitty-scratch
    workspace = special:terminal
    float = yes
    size = 1000 600
    center = yes
}

windowrule {
    name = scratchpad-btop
    match:class = kitty-btop
    workspace = special:btop
    float = yes
    size = 1000 600
    center = yes
}

windowrule {
    name = scratchpad-zeal
    match:class = org.zealdocs.zeal
    workspace = special:zeal
    float = yes
    size = 1000 600
    center = yes
}

# Example windowrules that are useful
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

