# ================================
# =========== Daemons ============
# ================================
exec-once = hyprpaper
exec-once = waybar
exec-once = mako

# ================================
# =========== Clipboard ==========
# ================================
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# ================================
# ============= Apps =============
# ================================
exec-once = [workspace 1 silent] kitty
exec-once = [workspace 2 silent] qutebrowser
exec-once = [workspace 3 silent] dolphin
exec-once = [workspace 9 silent] thunderbird
exec-once = [workspace 0 silent] tradingview

# ================================
# ============= Misc =============
# ================================
exec-once = ~/.config/theme/apply.sh

