# ================================
# =========== Variables ==========
# ================================
$browser = qutebrowser
$terminal = kitty
$email = thunderbird
$music = spotify
$chat = vesktop
$wallpaper = ~/.config/theme/wallpaper-picker.sh
$files = dolphin
