# --- Matugen Terminal Colors ---

# Grundfarben
foreground            #dee4df
background            #0f1512
selection_foreground  #00382a
selection_background  #88d6ba

# Cursor
cursor                #88d6ba
cursor_text_color     #00382a

# URL Farbe (passend zum Akzent)
url_color             #88d6ba

# Border (Fensterränder in Kitty)
active_border_color   #88d6ba
inactive_border_color #89938e
bell_border_color     #ffb4ab

# Tab bar - Passend zum Waybar Design
tab_bar_style               fade
tab_fade                    1
active_tab_foreground       #00382a
active_tab_background       #88d6ba
active_tab_font_style       bold
inactive_tab_foreground     #bfc9c3
inactive_tab_background     #171d1a
inactive_tab_font_style     normal
tab_bar_background          #0f1512

# --- ANSI Colors (Für CLI Tools wie btop, lsd, etc.) ---

# Black (Dunkelster Untergrund)
color0  #090f0d
color8  #343b38

# Red (Fehler/Warnungen)
color1  #ffb4ab
color9  #93000a

# Green (Erfolg/Strings)
color2  #a8cbe1
color10 #a8cbe1

# Yellow (Warnungen/Typen)
color3  #b2ccc1
color11 #b2ccc1

# Blue (Akzent/Keywords)
color4  #88d6ba
color12 #88d6ba

# Magenta
color5  #00513f
color13 #a4f2d6

# Cyan
color6  #344c43
color14 #cee9dc

# White (Textfarben)
color7  #bfc9c3
color15 #dee4df
