# Matugen generated colors
foreground #e8e2d4
background #15130c
selection_foreground #383000
selection_background #d9c76f

# Cursor
cursor #d9c76f
cursor_text_color #383000

# Black
color0 #15130c
color8 #3c3930

# Red
color1 #ffb4ab
color9 #ffb4ab

# Green
color2 #a8d0b4
color10 #a8d0b4

# Yellow
color3 #d0c7a2
color11 #d0c7a2

# Blue
color4 #d9c76f
color12 #d9c76f

# Magenta
color5 #2b4e39
color13 #a8d0b4

# Cyan
color6 #4d472b
color14 #d0c7a2

# White
color7 #e8e2d4
color15 #e8e2d4

# Tab bar
tab_bar_background #15130c
active_tab_foreground #383000
active_tab_background #d9c76f
inactive_tab_foreground #e8e2d4
inactive_tab_background #222017
