# --- Matugen Terminal Colors ---

# Grundfarben
foreground            #e8e2d4
background            #15130c
selection_foreground  #383000
selection_background  #d9c76f

# Cursor
cursor                #d9c76f
cursor_text_color     #383000

# URL Farbe (passend zum Akzent)
url_color             #d9c76f

# Border (Fensterränder in Kitty)
active_border_color   #d9c76f
inactive_border_color #969180
bell_border_color     #ffb4ab

# Tab bar - Passend zum Waybar Design
tab_bar_style               fade
tab_fade                    1
active_tab_foreground       #383000
active_tab_background       #d9c76f
active_tab_font_style       bold
inactive_tab_foreground     #ccc6b4
inactive_tab_background     #1e1c13
inactive_tab_font_style     normal
tab_bar_background          #15130c

# --- ANSI Colors (Für CLI Tools wie btop, lsd, etc.) ---

# Black (Dunkelster Untergrund)
color0  #100e07
color8  #3c3930

# Red (Fehler/Warnungen)
color1  #ffb4ab
color9  #93000a

# Green (Erfolg/Strings)
color2  #a8d0b4
color10 #a8d0b4

# Yellow (Warnungen/Typen)
color3  #d0c7a2
color11 #d0c7a2

# Blue (Akzent/Keywords)
color4  #d9c76f
color12 #d9c76f

# Magenta
color5  #524700
color13 #f6e388

# Cyan
color6  #4d472b
color14 #ede3bc

# White (Textfarben)
color7  #ccc6b4
color15 #e8e2d4
